### ISSUE TITLE
please drop this app!

### ISSUE THREAD

**Issue by cauerego** [shiftrot/caps2ctrl#2]
and focus on virtual keyboards for droidvim and droidemacs! 🤣
https://github.com/shiftrot/droidvim/issues/45

cheers! 😘

**Comment by shiftrot** [comment]
This app has nothing to do with DroidVim or software keyboard.

**Comment by cauerego** [comment]
you make both apps.

and you done this so you can better use physical keyboard on droid vim, didn't you?

it has everything to do with both points then.

and i'm just wishfully hoping you can instead use the same setup as i do... since you already came in so close! 😁😘

**Comment by shiftrot** [comment]
This app is for assigning functions to special keys on the Japanese physical keyboard that are not used on Android.
I'm not sure what your "the same setup" mean.
If you have any request, please specify.

**Comment by cauerego** [comment]
not sure you really want to know about specific requests.

i gave you A LOT of specifics on the link, and you just disregarded everything. if you even looked at it, you sure didn't show any positive reaction.

but, in short, my setup is linux on small screen android with virtual keyboard.

droidvim does a wonderful job at it.

it would be much better if we had such vkb on termux... and droidemacs, as already mentioned.
