### ISSUE TITLE
bug: Enterを押して改行すると全角に戻ってしまう

### ISSUE THREAD

**Issue by hengin-eer** [shiftrot/caps2ctrl#3]
文章中で改行すると半角入力中でも全角に戻ってしまいます
アプリ自体は非常に使い心地がいいために、途中で全角に戻ってしまうと悲しいです
何卒よろしくお願いします

**Comment by shiftrot** [comment]
まず以下について教えてください。
- 使用しているキーボードアプリ名
- 使用している本アプリのレイアウト名
- あなたのデバイスのOSバージョン

可能であればキーボードアプリはそのままで、他のアプリに含まれるキーレイアウト（例えばGboardの日本語109A配列）を使用して、同じ現象が起きるかどうか確かめていただけると助かります。

本アプリはOSに設定ファイルを追加するだけです。またEnterキー自体には何も設定していません。
したがって原理的にはEnterキーの挙動はあなたの使用しているキーボードアプリにのみ依存しているはずです。

いずれにせよ今は出先で物理キーボードが手元にないため、対応できるのは来週になると思います。申し訳ありません。

**Comment by hengin-eer** [comment]
当日に返信いただけるとは思ってませんでした！ありがとうございます。
以下ご質問の回答です
- Gboardです
- Caps → 半/全
- Android 13になります

日本語109に変更して試したところ、同様の挙動になりましたので、Gboardの仕様かと思われます
なのでGboardについて少し調べてみます
お忙しい中ご対応ありがとうございました🙇
